Add four more stretch goals
PrimeAcademy/assignment-unit-3.1 pull request #2
Opened 2022-01-20 18:03 UTC by eschwartz

Resolves #1 

These stretch goals are pushing students to look up built-in array methods that we haven't explicitly taught them.

Will update rubric, if this PR is approved

2022-01-20 18:04 UTC, eschwartz commented on assignment/scripts/array-practice.js
> +//      Then log the updated array.
favFoods.splice(1, 1, "bananas");
console.log(favFoods);

2022-01-20 18:04 UTC, eschwartz commented on assignment/scripts/array-practice.js
> +//     in reverse alphabetical order. Log the array.
`console.log(favFoods.sort().reverse());`

2022-01-20 18:05 UTC, eschwartz commented on assignment/scripts/array-practice.js
> +//     eg "tacos and pizza and pasta". Log the string.
```
console.log(favFoods.join(' and '));
```

2022-01-20 21:43 UTC, kdszafranski requested changes
add in `.concat()` !

2022-01-21 15:44 UTC, eschwartz commented on assignment/scripts/array-practice.js
> +//     eg "tacos and pizza and pasta". Log the string.
console.log(favFoods.join(' and '));

2022-01-21 15:44 UTC, eschwartz commented on assignment/scripts/array-practice.js
> +//     ['pizza', 'pasta', 'fish', 'cat', 'bird', 'dog']
```js
console.log(favFoods.concat(animalsArray));
```

2022-01-21 15:46 UTC, eschwartz commented
> add in .concat() !

https://github.com/PrimeAcademy/prime-pw-week-3-assignment-part-1/pull/2/files#diff-aff1dd259dec77cdfd14e04083011e0f06c597d4b87c8370114a3faea1ca33b9R90-R94

2022-01-28 15:38 UTC, kdszafranski commented
Since these are stretch goals, let's remove the examples for some, maybe the last 2 and guide them with: research XYZ

2022-02-23 18:45 UTC, kdszafranski approved these changes
let's do it!

2022-02-23 18:46 UTC, merged